/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUpdateDataRouteImport } from './routes/api/update-data'
import { Route as ApiFetchDataRouteImport } from './routes/api/fetch-data'
import { Route as ApiBatchUpdateRouteImport } from './routes/api/batch-update'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUpdateDataRoute = ApiUpdateDataRouteImport.update({
  id: '/api/update-data',
  path: '/api/update-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFetchDataRoute = ApiFetchDataRouteImport.update({
  id: '/api/fetch-data',
  path: '/api/fetch-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBatchUpdateRoute = ApiBatchUpdateRouteImport.update({
  id: '/api/batch-update',
  path: '/api/batch-update',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/batch-update': typeof ApiBatchUpdateRoute
  '/api/fetch-data': typeof ApiFetchDataRoute
  '/api/update-data': typeof ApiUpdateDataRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/batch-update': typeof ApiBatchUpdateRoute
  '/api/fetch-data': typeof ApiFetchDataRoute
  '/api/update-data': typeof ApiUpdateDataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/batch-update': typeof ApiBatchUpdateRoute
  '/api/fetch-data': typeof ApiFetchDataRoute
  '/api/update-data': typeof ApiUpdateDataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/batch-update' | '/api/fetch-data' | '/api/update-data'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/batch-update' | '/api/fetch-data' | '/api/update-data'
  id:
    | '__root__'
    | '/'
    | '/api/batch-update'
    | '/api/fetch-data'
    | '/api/update-data'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBatchUpdateRoute: typeof ApiBatchUpdateRoute
  ApiFetchDataRoute: typeof ApiFetchDataRoute
  ApiUpdateDataRoute: typeof ApiUpdateDataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/update-data': {
      id: '/api/update-data'
      path: '/api/update-data'
      fullPath: '/api/update-data'
      preLoaderRoute: typeof ApiUpdateDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fetch-data': {
      id: '/api/fetch-data'
      path: '/api/fetch-data'
      fullPath: '/api/fetch-data'
      preLoaderRoute: typeof ApiFetchDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/batch-update': {
      id: '/api/batch-update'
      path: '/api/batch-update'
      fullPath: '/api/batch-update'
      preLoaderRoute: typeof ApiBatchUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBatchUpdateRoute: ApiBatchUpdateRoute,
  ApiFetchDataRoute: ApiFetchDataRoute,
  ApiUpdateDataRoute: ApiUpdateDataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
